name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  specs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.3', '3.4', '4.0']
        rails: ['7.2', '8.0', '8.1']
        include:
          - {ruby: '4.0', rails: '_main'}
    name: ruby${{ matrix.ruby }} rails${{ matrix.rails }} rake test
    env:
      BUNDLE_GEMFILE: gemfiles/rails${{ matrix.rails }}.gemfile
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake test

  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: linter
        run: bundle exec rubocop

  specs_successful:
    name: Specs passing?
    needs: specs
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: |
          if ${{ needs.specs.result == ‘success’ }}
          then
            echo "All specs pass"
          else
            echo "Some specs failed"
            false
          fi
